spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  shardingsphere:
    datasource:
      names: ds0, ds1, ds2
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/sphere0?currentSchema=public
        jdbc-url: ${spring.shardingsphere.datasource.ds0.url}
        jdbcUrl: ${spring.shardingsphere.datasource.ds0.url}
        username: postgres
        password: 12345
        active: false
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5433/sphere0?currentSchema=public
        jdbc-url: ${spring.shardingsphere.datasource.ds0.url}
        jdbcUrl: ${spring.shardingsphere.datasource.ds0.url}
        username: postgres
        password: 12345
        active: false
      ds2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5434/sphere0?currentSchema=public
        jdbc-url: ${spring.shardingsphere.datasource.ds0.url}
        jdbcUrl: ${spring.shardingsphere.datasource.ds0.url}
        username: postgres
        password: 12345
        active: false
    rules:
      sharding:
        default-database-strategy:
          standard:
            sharding-column: time_operation
            sharding-algorithm-name: self-made-alg
        tables:
          userinfo:
            actual-data-nodes: ds$->{0..2}.userinfo
            table-strategy:
              standard:
                sharding-column: time_operation
                sharding-algorithm-name: userinfo
        sharding-algorithms:
          self-made-alg:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.example.shard.sharding.IntelligenceIntervalShardingAlgorithm
              clusterConfigPath: classpath:sharding/dev-cluster-info.yml
              dateFormat: "yyyy-MM-dd HH:mm:ss"
    props:
      sql-show: true
