cluster:
  - name: "ds0"
    active: false
    period:
      from: "2022-06-01"
      to: "2022-06-31"

  - name: "ds1"
    active: false
    period:
      from: "2022-06-31"
      to: "2022-07-10"

  - name: "ds2"
    active: true
    period:
      from: "2022-07-10"
      to: "now"