version: '3'
services:
  psql-1:
    image: postgres:latest
    container_name: db0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sphere0
      SCHEMA: public
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/dump.sql
  psql-2:
    image: postgres:latest
    container_name: db1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sphere0
      SCHEMA: public
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/dump.sql
  psql-3:
    image: postgres:latest
    container_name: db2
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sphere0
      SCHEMA: public
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/dump.sql